Repository csuntechlab/iSTART, pull requests merged in 2019-05, with the labels that each got.

#71 STR-139 -- DO:Remove Laravel Echo & Create a Local DB through Docker
  .env.example
  docker-compose.yml
Labels: mentor approval

#68 STR-95 -- BE: Create email for students when they are almost out of time with a module
  app/Contracts/UserRunningOutOfTimeEmailContract.php
  app/Http/Controllers/UserRunningOutOfTimeEmailController.php
  app/Mail/UserRunningOutOfTimeEmail.php
  app/Providers/EmailServiceProvider.php
  app/Services/UserCompletesModuleEmailService.php
  app/Services/UserRunningOutOfTimeEmailService.php
  config/app.php
  resources/views/mail/UserRunningOutOfTimeEmail.blade.php
  routes/web.php
Labels: final approval

#65 STR-100 -- BE: Remove someone from the study (remove them from the table)
  app/Contracts/ParticipantContract.php
  app/Models/Participant.php
  app/Services/ParticipantService.php
  database/factories/ParticipantFactory.php
  tests/phpunit/ServicesTests/ParticipantServiceTest.php
Labels: requires attention

#63 STR-94 -- BE: Create email for students when they finish a module
  app/Contracts/UserCompletesModuleEmailContract.php
  app/Http/Controllers/UserCompletesModuleEmailController.php
  app/Mail/UserCompletesModuleEmailToAdmin.php
  app/Mail/UserCompletesModuleEmailToStudent.php
  app/Services/UserCompletesModuleEmailService.php
  resources/views/mail/UserCompletesModuleEmail.blade.php
  resources/views/mail/UserCompletesModuleEmailToAdmin.blade.php
  resources/views/mail/UserCompletesModuleEmailToStudent.blade.php
  routes/web.php
Labels: requires attention

#75 STR-97--BE: Create email for iSTART when a student has been removed from the study
  app/Contracts/StudentRemovedFromStudyAdminEmailContract.php
  app/Http/Controllers/StudentRemovedFromStudyController.php
  app/Mail/StudentRemovedFromStudyAdminEmail.php
  app/Providers/StudentRemovedFromStudyAdminEmailServiceProvider.php
  app/Services/StudentRemovedFromStudyAdminEmailService.php
  config/app.php
  resources/views/mail/StudentRemovedFromStudyAdminEmail.blade.php
  routes/web.php
Labels: final approval

#69 STR-96--BE: Keep track of and send an email when student is almost out of time with a module
  app/Contracts/ModuleProgressContract.php
  app/Http/Controllers/ModuleProgressController.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Jobs/SendNewModuleEmail.php
  app/Jobs/SendReminderModuleEmail.php
  composer.json
  composer.lock
  routes/web.php
  tests/phpunit/ControllersTests/ModuleProgressControllerTest.php
Labels: final approval

#79 STR-128 --FE: Create informational slide template
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/templates/IntroSlide.vue
  resources/js/components/modules/templates/info/infoContent.vue
  resources/js/components/modules/templates/info/infoPhoto.vue
  resources/js/components/modules/templates/infoTemplate.vue
  resources/js/components/modules/templates/quiz/quizOption.vue
  resources/js/components/modules/templates/quizTemplate.vue
  resources/js/routes.js
  resources/js/views/Login.vue
  resources/js/views/Module.vue
  resources/sass/app.scss
  resources/sass/modules/_module.scss
  resources/sass/modules/templates/_informational.scss
  resources/views/welcome.blade.php
Labels: mentor approval

#77 STR-99--BE: Keep track of and send emails when a student is no longer in a study
  app/Http/Controllers/ParticipantController.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Jobs/RemoveParticipantFromStudy.php
  routes/web.php
  tests/phpunit/ControllersTests/ParticipantControllerTest.php
Labels: mentor approval

#74 STR-98--BE: Create email for Students when a student has been removed from the study
  app/Contracts/StudentRemovedFromStudyContract.php
  app/Contracts/UserCompletesModuleEmailContract.php
  app/Http/Controllers/StudentRemovedFromStudyController.php
  app/Mail/StudentRemovedFromStudy.php
  app/Providers/StudentRemovedFromStudyServiceProvider.php
  app/Services/StudentRemovedFromStudyService.php
  config/app.php
  resources/views/mail/StudentRemovedFromStudyEmail.blade.php
  routes/web.php
Labels: resolving issue

#70 STR-131 -- FE: Create card-flip template
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/templates/cardFlipTemplate.vue
  resources/js/views/Module.vue
  resources/sass/app.scss
  resources/sass/global/_base.scss
  resources/sass/modules/_module.scss
  resources/sass/modules/templates/_card-flip.scss
Labels: mentor approval, resolved

#84 STR-151 -- FE: Implement Embedded YouTube Video Slides #14, #16
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/alcoholModule.js
  resources/js/components/modules/templates/infoTemplate.vue
  resources/js/components/modules/templates/videoTemplate.vue
  resources/js/routes.js
  resources/js/views/Module.vue
Labels: mentor approval

#83 STR-142 -- FE: Multi-Question Multiple-Choice Survey Slide + Survey Feedback Slide Template
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/api/__mocks__/slides.js
  resources/js/api/slides.js
  resources/js/components/modules/moduleFooter.vue
  resources/js/components/modules/templates/MultiChoiceSurvey.vue
  resources/js/components/modules/templates/MultiChoiceSurveyResults.vue
  resources/js/store/modules/slides/actions.js
  resources/js/store/modules/slides/getters.js
  resources/js/store/modules/slides/mutations.js
  resources/js/store/modules/slides/state.js
  resources/js/views/Module.vue
  resources/sass/app.scss
  resources/sass/global/_base.scss
  resources/sass/modules/_module.scss
  resources/sass/modules/templates/_multi-choice-survey-results.scss
  resources/sass/modules/templates/_multi-choice-survey.scss
  resources/sass/modules/templates/_quiz.scss
  resources/views/mail/InfoFromModuleEmail.blade.php
  tests/jsUnit/storeModules/slides.spec.js
Labels: mentor approval

#87 STR-144 -- FE: Create Email form slide template
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/api/slides.js
  resources/js/components/modules/data/alcoholModule.js
  resources/js/components/modules/templates/MultiChoiceSurveyResults.vue
  resources/js/components/modules/templates/emailForm.vue
  resources/js/routes.js
  resources/js/views/Module.vue
  resources/sass/app.scss
  resources/sass/modules/templates/_email-form.scss
Labels: final approval

#86 STR-130 -- FE: Implement Slide #1 and #2 (intro) for the alcohol module
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/alcoholModule.js
  resources/js/components/modules/templates/IntroSlide.vue
  resources/js/views/Module.vue
Labels: final approval

#91 STR-160 -- FE: Update informational template to allow for different image placement
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/alcoholModule.js
  resources/js/components/modules/templates/info/infoPhoto.vue
  resources/js/components/modules/templates/infoTemplate.vue
  resources/sass/modules/templates/_informational.scss
Labels: final approval

#90 STR-145 -- FE: Implement Information Slide #20 with carousel
  public/css/app.css
  public/images/alcoholModule/alcohol_s20_01.png
  public/images/alcoholModule/alcohol_s20_02.png
  public/images/alcoholModule/alcohol_s20_03.png
  public/images/alcoholModule/alcohol_s20_04.png
  public/images/alcoholModule/alcohol_s20_05.png
  public/images/alcoholModule/alcohol_s20_06.png
  public/images/alcoholModule/alcohol_s20_07.png
  public/images/alcoholModule/alcohol_s20_08.png
  public/images/alcoholModule/alcohol_s20_09.png
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/alcoholModule.js
  resources/js/components/modules/templates/info/infoCarousel.vue
  resources/js/components/modules/templates/infoTemplate.vue
  resources/js/views/Module.vue
  resources/sass/global/_helpers.scss
  resources/sass/modules/templates/_informational.scss
Labels: final approval
