Repository csuntechlab/iSTART, pull requests merged in 2019-07, with the labels that each got.

#108 STR-183 -- FE: Implement revised notes for Alcohol module; last 11.
  public/css/app.css
  public/images/alcoholModule/alcohol_s18_03.png
  public/images/alcoholModule/alcohol_s18_04.png
  public/images/alcoholModule/alcohol_s28_01.jpg
  public/js/main.js
  public/mix-manifest.json
  resources/js/__mocks__/main.js
  resources/js/components/modules/data/modules/alcoholModule.js
  resources/js/components/modules/templates/EmailForm.vue
  resources/js/components/modules/templates/InfoTemplate.vue
  resources/js/components/modules/templates/info/InfoPhoto.vue
  resources/js/components/modules/templates/info/InfoPhotoList.vue
  resources/sass/templates/_card-flip.scss
  resources/sass/templates/_informational.scss
  resources/sass/templates/_photo-list.scss
Labels: final approval

#111 STR-191 -- FE: Go through 2nd revisions of Alcohol module
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/modules/alcoholModule.js
  resources/js/components/modules/templates/EmailForm.vue
  resources/js/components/modules/templates/InputComparisonTemplate.vue
  resources/js/components/modules/templates/InputPieChartTemplate.vue
  resources/js/components/modules/templates/input/InputPieChartLegend.vue
  resources/js/components/modules/templates/input/InputResponse.vue
  resources/sass/templates/_email-form.scss
  resources/sass/templates/_quizInput.scss
Labels: resolved

#117 STR-186 -- FE: Update application theme, represented by the latest mockup.
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/admin/Participants.vue
  resources/js/components/dashboard/DashboardModule.vue
  resources/js/components/dashboard/DashboardNotification.vue
  resources/js/components/global/CookiesNotification.vue
  resources/js/components/modules/templates/CardFlipTemplate.vue
  resources/js/components/modules/templates/InputComparisonTemplate.vue
  resources/js/components/modules/templates/IntroSlide.vue
  resources/js/components/modules/templates/VideoTemplate.vue
  resources/js/components/modules/templates/info/InfoList.vue
  resources/js/components/modules/templates/info/InfoParagraph.vue
  resources/js/components/modules/templates/info/InfoPhoto.vue
  resources/js/components/modules/templates/quiz/QuizQuestion.vue
  resources/js/views/Dashboard.vue
  resources/js/views/Login.vue
  resources/js/views/Module.vue
  resources/sass/components/_control.scss
  resources/sass/components/_dashboard.scss
  resources/sass/components/_module.scss
  resources/sass/components/_progress.scss
  resources/sass/global/_helpers.scss
  resources/sass/global/_variables.scss
  resources/sass/templates/_card-flip.scss
  resources/sass/templates/_image-grid.scss
  resources/sass/templates/_informational.scss
  resources/sass/templates/_introduction.scss
  resources/sass/templates/_multi-choice-survey.scss
  resources/sass/templates/_photo-list.scss
  resources/sass/templates/_quiz.scss
  resources/sass/templates/_quizInput.scss
  resources/sass/templates/_video-template.scss
Labels: resolved

#116 STR-212 -- Alcohol Module Revisions
  public/css/app.css
  public/images/alcoholModule/alcohol_s03_01.PNG
  public/images/alcoholModule/alcohol_s03_01.png
  public/images/alcoholModule/alcohol_s03_02.png
  public/images/alcoholModule/alcohol_s06_02.PNG
  public/images/alcoholModule/alcohol_s06_02.jpg
  public/images/thumbnail/alcohol_thumbnail.jpg
  public/images/thumbnail/illicit-drugs_thumbnail.jpg
  public/images/thumbnail/marijuana_thumbnail.jpg
  public/images/thumbnail/nicotine_thumbnail.jpg
  public/images/thumbnail/prescription-drugs_thumbnail.jpg
  public/images/thumbnail/test.jpg
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/dashboard/DashboardModule.vue
  resources/js/components/global/Navbar.vue
  resources/js/components/modules/ModuleFooter.vue
  resources/js/components/modules/data/modules/alcoholModule.js
  resources/js/components/modules/templates/EmailForm.vue
  resources/js/components/modules/templates/InputPieChartTemplate.vue
  resources/js/components/modules/templates/info/infoPhotoGrid.vue
  resources/js/mixins/awaitTimeBeforeContinue.js
  resources/js/views/Login.vue
  resources/js/views/Module.vue
  resources/sass/components/_login.scss
  yarn.lock
Labels: resolved

#115 STR-193 -- FE: Implement multi-module support
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/dashboard/DashboardModule.vue
  resources/js/components/modules/data/moduleSelector.js
  resources/js/components/modules/data/modules/test.js
  resources/js/store/modules/slides/actions.js
  resources/js/store/modules/slides/getters.js
  resources/js/store/modules/slides/mutations.js
  resources/js/store/modules/slides/state.js
  resources/js/views/Module.vue
Labels: requires attention
