Repository csuntechlab/iSTART, pull requests merged in 2019-06, with the labels that each got.

#92 STR-132 -- FE: Implement Information Slides #3, #4, #5, #10, #17 into Alcohol Module
  public/css/app.css
  public/images/alcoholModule/alcohol_s03_01.png
  public/images/alcoholModule/alcohol_s03_02.png
  public/images/alcoholModule/alcohol_s04_01.png
  public/images/alcoholModule/alcohol_s05_01.png
  public/images/alcoholModule/alcohol_s05_02.png
  public/images/alcoholModule/alcohol_s10_01.jpg
  public/images/alcoholModule/alcohol_s17_01.png
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/alcoholModule.js
  resources/js/components/modules/templates/infoTemplate.vue
  resources/sass/modules/templates/_informational.scss
Labels: final approval

#95 STR-165 -- FE: Fix informational slide list
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/alcoholModule.js
  resources/js/components/modules/templates/info/infoContent.vue
  resources/js/components/modules/templates/info/infoList.vue
  resources/js/components/modules/templates/infoTemplate.vue
Labels: final approval

#93 STR-152 -- FE: Implement Email Form Slide #32
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/alcoholModule.js
  resources/js/components/modules/templates/emailForm.vue
Labels: requires attention

#88 STR-141 -- FE: Create Multi-Question text-input (1-100) Quiz Slide + Answer Slide template
  package.json
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/moduleHeader.vue
  resources/js/components/modules/templates/infoTemplate.vue
  resources/js/components/modules/templates/pieChartTemplate.vue
  resources/js/components/modules/templates/quiz/quizInput.vue
  resources/js/components/modules/templates/quiz/quizLegend.vue
  resources/js/components/modules/templates/quiz/quizOption.vue
  resources/js/components/modules/templates/quizInputTemplate.vue
  resources/js/components/modules/templates/quizTemplate.vue
  resources/js/components/modules/templates/videoTemplate.vue
  resources/js/main.js
  resources/js/routes.js
  resources/js/store/modules/slides/actions.js
  resources/js/store/modules/slides/getters.js
  resources/js/store/modules/slides/mutations.js
  resources/js/store/modules/slides/state.js
  resources/js/store/modules/user/mutations.js
  resources/js/views/Login.vue
  resources/js/views/Module.vue
  resources/sass/app.scss
  resources/sass/modules/templates/_quizInput.scss
  tests/jsUnit/components/modules/template.spec.js
  tests/jsUnit/storeModules/slides.spec.js
  yarn.lock
Labels: final approval

#102 STR-167 -- FE: Fix introduction template to be mobile responsive
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/data/modules/alcoholModule.js
  resources/js/components/modules/templates/IntroSlide.vue
  resources/sass/templates/_introduction.scss
Labels: resolved

#101 STR-177 -- FE: Fix quiz indicator should only pop up for answer selected
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/modules/templates/quiz/QuizQuestion.vue
Labels: final approval

#103 STR-168 -- FE: Fix tab Accessibility on Dashboard and main navigation
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/global/Navbar.vue
  resources/sass/components/_navbar.scss
Labels: merge conflict
