Repository csuntechlab/iSTART, pull requests merged in 2019-04, with the labels that each got.

#42 STR-54 -- FE: Create the admin page with the ability to take in an excel sheet and pass it to the backend
  package.json
  public/js/main.js
  public/mix-manifest.json
  resources/js/api/__mocks__/admin.js
  resources/js/api/admin.js
  resources/js/store/index.js
  resources/js/store/modules/admin/actions.js
  resources/js/store/modules/admin/getters.js
  resources/js/store/modules/admin/index.js
  resources/js/store/modules/admin/mutations.js
  resources/js/store/modules/admin/state.js
  resources/js/views/admin.vue
  tests/jsUnit/store_modules/admin.spec.js
  tests/jsUnit/views/admin.spec.js
  yarn.lock
Labels: mentor approval

#43 STR-71 -- FE: Hamburger Menu does not fill up all the way at once
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/global/navbar.vue
  resources/js/views/Error.vue
  resources/js/views/admin.vue
  resources/sass/global/_helpers.scss
  resources/sass/global/_navbar.scss
  tests/jsUnit/global/navbar.spec.js
Labels: final approval, resolved

#44 STR-25--BE: Send and email to the "Client" when a student completes a module
  .env.example
  app/Contracts/UserCompletesModuleEmailContract.php
  app/Http/Controllers/UserCompletesModuleEmailController.php
  app/Mail/UserCompletesModuleEmail.php
  app/Models/Research.php
  app/Providers/UserCompletesModuleEmailServiceProvider.php
  app/Services/AuthenticationService.php
  app/Services/UserCompletesModuleEmailService.php
  config/app.php
  resources/views/mail/UserCompletesModuleEmail.blade.php
  routes/web.php
Labels: mentor approval

#47 STR-55 -- BE: Take a JSON and check the email field one by one to see if the email is valid
  app/Contracts/AdminContract.php
  app/Http/Controllers/AdminController.php
  app/ModelRepositories/UserModelRepository.php
  app/ModelRepositoryInterfaces/UserModelRepositoryInterface.php
  app/Providers/AdminServiceProvider.php
  app/Providers/ModelRepositoryServiceProvider.php
  app/Services/AdminService.php
  composer.json
  config/app.php
  routes/web.php
  tests/phpunit/ControllersTests/AdminControllerTest.php
  tests/phpunit/ControllersTests/LoginControllerTest.php
  tests/phpunit/ServicesTests/AdminServiceTest.php
Labels: mentor approval

#41 STR-57--BE:Send an email to the "Client" when a student becomes assigned to a group
  app/Contracts/UserAssignedGroupEmailContract.php
  app/Http/Controllers/MailController.php
  app/Http/Controllers/UserGroupController.php
  app/Mail/GenericEmail.php
  app/Providers/UserAssignedGroupEmailServiceProvider.php
  app/Services/AuthenticationService.php
  app/Services/UserAssignedGroupEmailService.php
  app/Services/UserGroupService.php
  config/app.php
  config/mail.php
  resources/views/mail/generic.blade.php
  tests/phpunit/ServicesTests/UserGroupServiceTest.php
Labels: mentor approval

#46 STR-86 -- FE: Service Worker Errors on yarn prod
  docker-compose.yml
  public/js/main.js
  public/mix-manifest.json
  resources/js/main.js
  resources/js/registerServiceWorker.js
Labels: mentor approval, resolved

#51 STR-76 -- FE: Create desktop version of Login page
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/views/Login.vue
  resources/sass/global/_base.scss
  resources/sass/global/_forms.scss
  resources/sass/global/_layout.scss
  resources/sass/global/_variables.scss
  resources/sass/modules/_login.scss
Labels: final approval, resolved

#45 STR-59 -- FE: Ensure all front-end code conforms to our current naming convention we agreed upon.
  public/js/main.js
  public/mix-manifest.json
  resources/js/App.vue
  resources/js/components/global/Navbar.vue
  resources/js/components/schedule/ScheduleModules.vue
  resources/js/router.js
  resources/js/routes.js
  resources/js/store/modules/user/actions.js
  resources/js/views/Admin.vue
  resources/js/views/Schedule.vue
  tests/jsUnit/storeModules/admin.spec.js
  tests/jsUnit/storeModules/login.spec.js
  tests/jsUnit/views/admin.spec.js
Labels: final approval

#52 STR - 87 -- FE: Display "good" and "bad" research json and ask admin user whether to submit or not
  public/js/main.js
  public/mix-manifest.json
  resources/js/api/__mocks__/user.js
  resources/js/api/user.js
  resources/js/components/admin/Participants.vue
  resources/js/store/index.js
  resources/js/store/modules/admin/actions.js
  resources/js/store/modules/admin/getters.js
  resources/js/store/modules/admin/index.js
  resources/js/store/modules/admin/state.js
  resources/js/store/modules/user/actions.js
  resources/js/store/modules/user/getters.js
  resources/js/store/modules/user/mutations.js
  resources/js/store/modules/user/state.js
  resources/js/views/Admin.vue
  tests/jsUnit/storeModules/admin.spec.js
  tests/jsUnit/storeModules/login.spec.js
  tests/jsUnit/views/admin.spec.js
Labels: mentor approval, resolved

#53 STR-48 -- FE: Add notification to ensure cookies are enabled
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/App.vue
  resources/js/components/admin/Participants.vue
  resources/js/components/global/CookiesNotification.vue
  resources/js/views/Admin.vue
  resources/js/views/Login.vue
  resources/sass/app.scss
  resources/sass/modules/_cookies-notification.scss
Labels: mentor approval

#56 STR-65 -- FE: Create loading feedback for login
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/store/modules/user/actions.js
  resources/js/store/modules/user/getters.js
  resources/js/store/modules/user/mutations.js
  resources/js/store/modules/user/state.js
  resources/js/views/Login.vue
  resources/sass/components/_progress.scss
  resources/sass/modules/_login.scss
  tests/jsUnit/components/login/login.spec.js
Labels: mentor approval

#40 HOTFIX-3-27-2019--addForceHTTPS
  .env.example
  app/Http/Kernel.php
  composer.json
  composer.lock
  config/app.php
  config/forcehttps.php
Labels: mentor approval, resolved

#54 STR-88--BE: Upload "good" research json to the participant_id table
  app/Contracts/AdminContract.php
  app/Contracts/ParticipantContract.php
  app/Contracts/ResearchContract.php
  app/Http/Controllers/AdminController.php
  app/Http/Controllers/MailController.php
  app/Http/Controllers/ParticipantController.php
  app/Http/Middleware/VerifyCsrfToken.php
  app/Models/Participant.php
  app/Models/User.php
  app/Providers/ParticipantServiceProvider.php
  app/Services/AdminService.php
  app/Services/AuthenticationService.php
  app/Services/ParticipantService.php
  app/Services/ResearchService.php
  app/Services/UserAssignedGroupEmailService.php
  app/Services/UserCompletesModuleEmailService.php
  config/app.php
  database/factories/ParticipantFactory.php
  database/factories/ResearchFactory.php
  database/migrations/2019_03_05_014722_create_participant_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/ParticipantSeeder.php
  database/seeds/ResearchSeeder.php
  resources/views/mail/UserCompletesModuleEmail.blade.php
  resources/views/mail/generic.blade.php
  routes/web.php
  tests/phpunit/ServicesTests/AuthenticationServiceTest.php
  tests/phpunit/ServicesTests/ParticipantServiceTest.php
  tests/phpunit/ServicesTests/ResearchServiceTest.php
Labels: mentor approval, resolving issue

#66 STR-107 -- FE: Front end middle-ware should not take you to 404 pages, but rather redirect you to where you were
  public/js/main.js
  public/mix-manifest.json
  resources/js/main.js
  resources/js/router.js
  resources/js/routes.js
  resources/js/store/modules/user/mutations.js
  resources/js/views/Error.vue
  resources/js/views/Module.vue
Labels: merge conflict

#60 STR-110 -- BE: Email about group is sent out on every log in, not when the user is assigned to the group
  app/Services/UserGroupService.php
Labels: requires attention

#49 STR-90--BE: Make middleware on backend router
  app/Exceptions/Handler.php
  app/Http/Kernel.php
  routes/web.php
Labels: mentor approval
