Repository csuntechlab/iSTART, pull requests merged in 2019-03, with the labels that each got.

#18 STR-51 -- FE: Setup Jest Extended
  package-lock.json
  package.json
  tests/jsUnit/app.spec.js
  tests/jsUnit/components/login/login-form.spec.js
  tests/jsUnit/store_modules/login.spec.js
  yarn.lock
Labels: resolved

#25 STR-37 -- FE: Create Calendar page with "dummy" items listed (The skeleton for a list)
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/schedule/schedule-modules.vue
  resources/js/router.js
  resources/js/views/schedule.vue
  resources/sass/app.scss
  resources/sass/modules/_page.scss
  resources/sass/modules/_schedule.scss
Labels: resolved

#22 STR-21 -- FE: Create routing for user to the their splash page based on their role
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/App.vue
  resources/js/api/__mocks__/user.js
  resources/js/api/user.js
  resources/js/components/dashboard/ComparisonGroup.vue
  resources/js/components/dashboard/ControlGroup.vue
  resources/js/components/dashboard/DashboardModules.vue
  resources/js/components/dashboard/DashboardNotification.vue
  resources/js/components/dashboard/InterventionGroup.vue
  resources/js/components/global/navbar.vue
  resources/js/main.js
  resources/js/router.js
  resources/js/store/modules/user/actions.js
  resources/js/store/modules/user/mutations.js
  resources/js/views/Dashboard.vue
  resources/js/views/Login.vue
  resources/js/views/Logout.vue
  resources/js/views/Welcome.vue
  resources/js/views/login.vue
  resources/sass/global/_base.scss
  resources/sass/global/_helpers.scss
  resources/sass/global/_layout.scss
  resources/sass/modules/_dashboard.scss
  resources/sass/modules/_login.scss
  tests/jsUnit/components/login/login.spec.js
  tests/jsUnit/global/navbar.spec.js
  tests/jsUnit/store_modules/login.spec.js
Labels: resolved

#27 STR-72 -- FE: Clicking on modules in the modules page causes the hashtag to appear
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/global/navbar.vue
  resources/js/router.js
Labels: resolved

#36 STR-47 -- FE: Login for admin users
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/dashboard/DashboardModules.vue
  resources/js/router.js
  resources/js/store/modules/user/actions.js
  resources/js/views/Dashboard.vue
  resources/js/views/Error.vue
  resources/js/views/Logout.vue
  resources/js/views/admin.vue
  resources/js/views/schedule.vue
  tests/jsUnit/app.spec.js
  tests/jsUnit/store_modules/login.spec.js
Labels: resolved

#34 STR-53 -- FE: Create sass variables for our color pallet in our application
  public/css/app.css
  public/mix-manifest.json
  resources/js/components/global/navbar.vue
  resources/js/main.js
  resources/sass/global/_buttons.scss
  resources/sass/global/_helpers.scss
  resources/sass/global/_layout.scss
  resources/sass/global/_navbar.scss
  resources/sass/global/_variables.scss
  resources/sass/modules/_dashboard.scss
  resources/sass/modules/_error.scss
  resources/sass/modules/_login.scss
  resources/sass/modules/_schedule.scss
Labels: mentor approval, resolved

#32 STR-28 -- FE: Create Generic Module Thumbnail for dashboard that can be extended by other modules
  public/css/app.css
  public/images/test.jpg
  public/images/thumbnail/test.jpg
  public/js/main.js
  public/mix-manifest.json
  resources/js/components/dashboard/ComparisonGroup.vue
  resources/js/components/dashboard/ControlGroup.vue
  resources/js/components/dashboard/DashboardModule.vue
  resources/js/components/dashboard/DashboardModules.vue
  resources/js/components/dashboard/InterventionGroup.vue
  resources/js/views/Dashboard.vue
  resources/sass/global/_variables.scss
  resources/sass/modules/_dashboard.scss
Labels: mentor approval, resolved

#38 STR-80 -- FE: Research and install a progress bar library
  package.json
  public/css/app.css
  public/js/main.js
  public/mix-manifest.json
  resources/js/main.js
  resources/js/views/Dashboard.vue
  resources/js/views/admin.vue
  resources/sass/app.scss
  yarn.lock
Labels: mentor approval

#39 STR-75 -- FE: Check authentication for Vue routes
  public/js/main.js
  public/mix-manifest.json
  resources/js/App.vue
  resources/js/__mocks__/main.js
  resources/js/main.js
  resources/js/router.js
  resources/js/routes.js
  resources/js/store/index.js
  tests/jsUnit/router.spec.js
Labels: resolved
